language: node_js

node_js:
  - '6'
  - '5'

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

before_install:
  - npm prune

env:
  global:
    - NODE_ENV=development

notifications:
  email: false